          
            services:
              db:
                image: postgres:latest
                environment:
                  POSTGRES_USER: postgres
                  POSTGRES_PASSWORD: password
                  POSTGRES_DB: food-delivery
                ports:
                  - "5433:5432"


              app:
                build:
                  context: .
                  dockerfile: Dockerfile
                image: tech-task-24
                depends_on:
                  - db
                ports:
                  - "8080:8080"
                environment:
                  DATABASE_URL: "postgres://postgres:password@db:5432/food-delivery?sslmode=disable"
